#!/usr/bin/env python3
"""Learning cards generated only from the manuals (Phase P7.4): fill-in-the-number cards and multiple-choice questions.

Each card is one sentence of one paragraph in which exactly one measured value (a number with a unit) is hidden:

    front    the sentence with the value replaced by "_____", plus manual, chapter and paragraph
    answer   the value exactly as written in the manual
    options  the answer and three other values with the same unit from the same manual (distractors; they are other manual values, not facts about this sentence)
    source   paragraph id, manual, paragraph number, page; the full sentence is the explanation

No card text is written by hand and nothing is generated by a model: a card exists only if the sentence is a verbatim slice of the paragraph and
the hidden value is a measurement the extractor found at that exact place. `tests/test_learning.py` checks this for every card.

    python scripts/build_learning.py     # writes data/learning/cards.json, cards.js and coverage.json
"""

from __future__ import annotations

import hashlib
import json
import math
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
KG = ROOT / "data" / "knowledge-graph"
OUT_DIR = ROOT / "data" / "learning"
ALIASES = {"IRPWM", "TMM", "STMM", "USFD", "AT_WELD", "FBW"}
UNITS = {"mm", "cm", "m", "km", "kmph", "kg", "t", "%", "deg", "degC", "day", "days", "month", "months", "year", "years", "hour", "hours",
         "minute", "minutes", "second", "kn", "kN", "mpa", "MPa", "khz", "kHz", "mhz", "MHz", "gmt", "GMT", "kg/m", "mm/m", "g"}
WORDS = (8, 45)
MAX_CHARS = 330
NUMBER = re.compile(r"\d")
ABBR = re.compile(r"(?:^|[\s(/])(?:[A-Za-z]|No|Nos|Sr|Jr|Fig|Figs|Dr|Mr|Drg|Rly|Rlys|Dy|Dept|etc|viz|vs|approx|max|min|ref|para|sl|km|dia)$", re.I)


def read_jsonl(p: Path) -> list[dict]:
    return [json.loads(l) for l in p.read_text(encoding="utf-8").splitlines() if l.strip()]


def sentence_bounds(text: str) -> list[tuple[int, int]]:
    """Sentence spans of `text` (same splitting rule as the chat: after . ; : ? ! before a capital, bracket or digit)."""
    bounds, last = [], 0
    for m in re.finditer(r"[.;:?!]\s+(?=[A-Z(\d])", text):
        if m.group(0)[0] == "." and ABBR.search(text[max(0, m.start() - 8):m.start()]):
            continue
        bounds.append((last, m.start() + 1))
        last = m.end()
    bounds.append((last, len(text)))
    return bounds


CORE = re.compile(r"\d[\d.,]*(?:\s*(?:to|-|–)\s*\d[\d.,]*)?\s*[A-Za-z%°˚]+(?:/[A-Za-z]+)?")


def core_span(raw: str) -> tuple[int, int] | None:
    """The number and its unit inside a measurement's raw text ('not exceed 100 metres' -> '100 metres'); wording stays in the sentence."""
    found = list(CORE.finditer(raw))
    return (found[-1].start(), found[-1].end()) if found else None


def canonical(core: str) -> str:
    """Spelling-independent form of a value, so '4MHz' and '4 MHz', or 'metres' and 'meters', count as the same value."""
    t = re.sub(r"\s+", "", core.lower())
    t = re.sub(r"(metres?|meters?)$", "m", t)
    t = re.sub(r"(millimetres?|millimeters?)$", "mm", t)
    t = re.sub(r"(kilometres?|kilometers?)$", "km", t)
    t = re.sub(r"(kmph|km/h|kmh|kmps)$", "kmph", t)
    t = re.sub(r"(minutes?|mins?)$", "min", t)
    t = re.sub(r"(months?)$", "mon", t)
    t = re.sub(r"(years?)$", "yr", t)
    t = re.sub(r"(days?)$", "day", t)
    t = re.sub(r"(hours?|hrs?)$", "hr", t)
    t = re.sub(r"\b0+(\d)", r"\1", t)
    return re.sub(r"(\d)\.0+(?=\D|$)", r"\1", t)


def numeric_value(m: dict) -> float:
    return float(m["hi"] if m.get("hi") is not None else m["lo"])


def build() -> list[dict]:
    nodes = {n["id"]: n for n in read_jsonl(KG / "canonical" / "nodes.jsonl") if n["id"].startswith(("CLAUSE:", "CHAPTER:"))}
    meas = [m for m in read_jsonl(KG / "canonical" / "measurements.jsonl") if m["source"] == "text" and m["context"] == "prose"
            and m.get("unit") in UNITS and m["clause"] in nodes]
    by_clause: dict[str, list[dict]] = {}
    for m in meas:
        by_clause.setdefault(m["clause"], []).append(m)
    pool: dict[tuple[str, str], list[dict]] = {}          # (alias, unit) -> measurements, for distractors
    for m in meas:
        pool.setdefault((m["clause"].split(":")[1], m["unit"]), []).append(m)

    cards = []
    for cid in sorted(by_clause):
        alias = cid.split(":")[1]
        if alias not in ALIASES:
            continue
        text = nodes[cid]["text"]
        spans = sentence_bounds(text)
        best = None
        for m in by_clause[cid]:
            if text[m["start"]:m["end"]] != m["raw"]:
                continue
            sb = next(((a, b) for a, b in spans if a <= m["start"] and m["end"] <= b), None)
            if sb is None:
                continue
            sent = text[sb[0]:sb[1]]
            flat = " ".join(sent.split())
            n_words = len(flat.split())
            if not (WORDS[0] <= n_words <= WORDS[1]) or len(flat) > MAX_CHARS or "(Back to" in sent or "\n\n" in sent:
                continue
            inside = [x for x in by_clause[cid] if sb[0] <= x["start"] and x["end"] <= sb[1]]
            if len(inside) != 1 or len(NUMBER.findall(re.sub(r"\b[A-Z]{1,3}[-/ ]?\d+\b", "", sent))) > 3 * len(NUMBER.findall(m["raw"])) + 2:
                continue            # more than one hidden-able value, or many other numbers: the blank would be ambiguous
            if m["raw"].strip().isdigit() and len(m["raw"].strip()) <= 1:
                continue
            if best is None or n_words < best[0]:
                best = (n_words, m, sb, sent)
        if best is None:
            continue
        _, m, sb, sent = best
        cs = core_span(m["raw"])
        if cs is None:
            continue
        core = " ".join(m["raw"][cs[0]:cs[1]].split())
        abs_start, abs_end = m["start"] + cs[0], m["start"] + cs[1]
        before, after = text[abs_start - 1:abs_start], text[abs_end:abs_end + 1]
        if before.isdigit() or before in "/-" or after.isdigit() or after in "/" or after == "-":
            continue            # the value is glued to something else ("70/2 MHz"): blanking it would break the sentence
        target = numeric_value(m)
        if target == 0:
            continue
        cands = [x for x in pool[(alias, m["unit"])] if x["clause"] != cid and core_span(x["raw"])]
        seen, picks = {canonical(core)}, []
        for x in sorted(cands, key=lambda x: (abs(math.log((abs(numeric_value(x)) or 1e-9) / abs(target))), x["raw"], x["clause"])):
            xs = core_span(x["raw"])
            r = " ".join(x["raw"][xs[0]:xs[1]].split())
            if canonical(r) not in seen:
                seen.add(canonical(r))
                picks.append(r)
            if len(picks) == 3:
                break
        if len(picks) < 3:
            continue
        chapter = nodes.get(nodes[cid].get("parent_chapter_id"), {}).get("label", "")
        blanked = text[sb[0]:abs_start] + "_____" + text[abs_end:sb[1]]
        words_before = len(text[sb[0]:abs_start].split())
        if sent.count("[") != sent.count("]") or sent.count("(") != sent.count(")") or re.search(r"\b(?:Fig|Figs|No|Sl)\.?$", sent.strip()):
            continue            # a cut-off sentence or one with an unbalanced bracket
        if words_before < 4 or re.search(r"(?:\b[ivx]{1,4}|\b[a-z]|\d)\.$", " ".join(sent.split())) or len(blanked.split()) < 9:
            continue
        key = int(hashlib.sha256(cid.encode()).hexdigest(), 16)
        options = picks + [core]
        order = sorted(range(4), key=lambda i: hashlib.sha256(f"{cid}:{options[i]}".encode()).hexdigest())
        cards.append({
            "id": "CARD:" + cid.split(":", 1)[1], "clause": cid, "manual": alias, "para": str(nodes[cid]["specs"]["Paragraph"]),
            "page": nodes[cid]["page"], "chapter": chapter, "sentence": " ".join(sent.split()), "front": " ".join(blanked.split()),
            "answer": core, "unit": m["unit"], "options": [options[i] for i in order],
            "correct": order.index(3), "measurement": m["measurement_id"], "start": sb[0], "end": sb[1], "_k": key % 1000,
        })
    for c in cards:
        c.pop("_k")
    return cards


def main() -> int:
    cards = build()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "cards.json").write_text(json.dumps(cards, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    js = "(typeof window!=='undefined'?window:globalThis).RDSO_CARDS=" + json.dumps(cards, separators=(",", ":"), ensure_ascii=False) + ";\n"
    (OUT_DIR / "cards.js").write_text(js, encoding="utf-8")
    per = {}
    for c in cards:
        per[c["manual"]] = per.get(c["manual"], 0) + 1
    # where the cards do not reach: paragraphs and chapters per manual (a knowledge-gap view of the learning content, not of the manuals)
    nodes = [n for n in read_jsonl(KG / "canonical" / "nodes.jsonl") if n["id"].startswith(("CLAUSE:", "CHAPTER:"))]
    cov: dict[str, dict] = {}
    for n in nodes:
        a = n["id"].split(":")[1]
        if a not in ALIASES:
            continue
        d = cov.setdefault(a, {"paragraphs": 0, "cards": per.get(a, 0), "chapters": 0, "chapters_without_cards": []})
        if n["id"].startswith("CLAUSE:"):
            d["paragraphs"] += 1
        else:
            d["chapters"] += 1
            if not any(c["clause"].startswith(f"CLAUSE:{a}:{n['id'].split(':')[2]}:") for c in cards):
                d["chapters_without_cards"].append(n["id"].split(":")[2])
    for d in cov.values():
        d["share_of_paragraphs_with_a_card"] = round(d["cards"] / d["paragraphs"], 3) if d["paragraphs"] else 0
    (OUT_DIR / "coverage.json").write_text(json.dumps(dict(sorted(cov.items())), indent=1) + "\n", encoding="utf-8")
    print(f"{len(cards)} cards {dict(sorted(per.items()))} -> data/learning/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
